In [ ]:
a = [1,2,3,4] #List
b = (1,2,3,4) #Tuple

In [ ]:
#Now for converting list to array, we need numpy library
import numpy as np
c = np.array(a)
print(c)

[1 2 3 4]


In [ ]:
print(type(c))

<class 'numpy.ndarray'>


In [ ]:
#Similarly, for tuple
d = np.array(b)
print(d)
print(type(d))

[1 2 3 4]
<class 'numpy.ndarray'>


Remember, array does not contain any comma (,) where as in list, tuple, etc. you will find array.

In [ ]:
#Shape of the array
print(c.shape)

(4,)


4 rows, 0 columns (it's in 1 Dimension)

In [ ]:
#ndim tells dimension of array
print(c.ndim)
print(d.ndim)

1
1


These arrays are 1 dimension, so it's showing 1

In [ ]:
#reshape changes the shape of the array
e = c.reshape(2,2)
print(e)
print(e.ndim)
print(e.shape)

[[1 2]
 [3 4]]
2
(2, 2)


Syntax fof reshape() is reshape(no of rows, no of columns)

Remember, array treats set as a single element. So, there is no dimension. It will be zero dimemsion.

In [ ]:
try:
  f = {1,2,3,4}
  g = np.array(f)
  print(g)
  print(type(g))
  print(g.reshape(2,2))

except:
  print("ValueError: cannot reshape array of size 1 into shape (2,2)")

{1, 2, 3, 4}
<class 'numpy.ndarray'>
ValueError: cannot reshape array of size 1 into shape (2,2)


In [ ]:
print(g)
print(type(g))
print(g.ndim)
print(g.shape)

{1, 2, 3, 4}
<class 'numpy.ndarray'>
0
()


## 2D Array

In [ ]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.ndim)
print(a.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
a.dtype

dtype('int64')

In [ ]:
#I need float type array or object type array
a = np.array([[1,2,3],[4,5,6]],
             dtype = 'float')
print(a)
print(a.ndim)
print(a.shape)

b = np.array([[1,2,3],[4,5,6]],
             dtype = 'object')
print(b)
print(b.ndim)
print(b.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
2
(2, 3)
[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [ ]:
b.dtype

dtype('O')

In [1]:
# Forming array using inbuild functions

In [5]:
# Arange function
import numpy as np
print(np.arange(1,11))
print(np.arange(10))
print(np.arange(10, dtype='int64'))

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
a = np.arange(10, dtype='int64')
print(a.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
a = np.arange(10, dtype='int64')
print(a.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
# Identity matrix
a = np.identity(5, dtype='object')
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [10]:
# Random matrix
b = np.random.random((3,3))

In [11]:
print(b)

[[0.42640624 0.62361161 0.24229492]
 [0.88143879 0.75633482 0.88599466]
 [0.24923723 0.46668818 0.32756624]]


In [13]:
# Random non decimal matrix
np.random.randint(10)

5