# NUMPY.

In [ ]:
import numpy as np

In [ ]:
a= [1,2,3,4]
b= (1,2,3,4)

In [ ]:
#Convert list to array
c= np.array(a)
print(c)
print(type(c))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#Convert Tuple to array
d= np.array(b)
print(d)
print(type(d))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
print(c)

[1 2 3 4]


In [ ]:
#shape - tell shape of array

print(c.shape)
print(d.shape)

(4,)
(4,)


In [ ]:
# ndim - tells dimension of array
print(c.ndim)
print(d.ndim)

1
1


In [ ]:
# reshape  (1d- 2d)  - to change the shape of array

e= c.reshape(2,2)
print(e)
print(e.ndim)


[[1 2]
 [3 4]]
2


In [ ]:
s= {1,2,3,4}

In [ ]:
q= np.array(s)

In [ ]:
q

array({1, 2, 3, 4}, dtype=object)

In [ ]:
print(q.shape)

()


In [ ]:
q.ndim

0

In [ ]:
q.reshape(2,2)

ValueError: cannot reshape array of size 1 into shape (2,2)

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
c[3]

4

In [ ]:
np.array([1]).ndim

1

In [ ]:
#2D ARRAY
np.array([[1,2,3],[4,5,6]])

2

In [ ]:
#3D ARRAY
np.array([[[[1,2,3],[4,5,6]]]])

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [ ]:
c.dtype

dtype('int32')

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
# dtype

a= np.array([1,2,3,4], dtype= "object")

In [ ]:
a.dtype

dtype('O')

In [ ]:
a

array([1, 2, 3, 4], dtype=object)

In [ ]:
# form array using inbuild functions.

In [ ]:
# arange
print(np.arange(10))
print(np.arange(4,10))
print(np.arange(2,10,2))
a= np.arange(10, dtype= "int64")

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[2 4 6 8]


In [ ]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]], dtype=int64)

In [ ]:
np.arange(40).reshape(2,5,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]]],


       [[[20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]]]])

In [ ]:
# np.ones   - create a matrix where every element is 1.
print(np.ones(5))
print()
print(np.ones((3,3)))
print()
print(np.ones((3,3), dtype ="object"))

[1. 1. 1. 1. 1.]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#  np.zero   - create a matrix where every element is 0.
print(np.zeros(5))
print()
print(np.zeros((4,4)))
print()
print(np.zeros((4,4), dtype = "object"))

[0. 0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# np.full  - creates an array out of desired number.

print(np.full(5,12))
print()
print(np.full((5,5),24))
print()
print(np.full((4,4), 68, dtype= "float"))

[12 12 12 12 12]

[[24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]
 [24 24 24 24 24]]

[[68. 68. 68. 68.]
 [68. 68. 68. 68.]
 [68. 68. 68. 68.]
 [68. 68. 68. 68.]]


In [ ]:
# Identity matrix.
np.identity(5, dtype= "object")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=object)

In [ ]:
#  random matrix of decimal number
np.random.random((4,4))   #every element will be between 0-1

array([[0.47535626, 0.73605195, 0.31999925, 0.82686374],
       [0.95205338, 0.30153352, 0.20046685, 0.50557463],
       [0.64328298, 0.8760743 , 0.59954704, 0.15877962],
       [0.57611951, 0.16375959, 0.19108181, 0.93853848]])

In [ ]:
# non decimal matrix
print(np.random.randint(10))  #random number between 1-10
print()
print(np.random.randint(30,51))
print()
print(np.random.randint(1,20, size=(3,3)))
print()
print(np.random.randint(1,100, size=(4,5,6)))

8

50

[[16  8 13]
 [16 15 13]
 [ 7 14 10]]

[[[32 93 60 23 58  8]
  [ 8 44  9 79 12 31]
  [75  5 51 14 53 39]
  [ 1 63 78 17 84 24]
  [39 68 58 98 50 24]]

 [[ 2 52 40 58 17 48]
  [63 15 54  2 14 90]
  [96 42 22 59 86 60]
  [86 12 87 47 59 42]
  [28 50 42 22 11 69]]

 [[31 34  9 17 66  9]
  [ 7 98 82 47 83 57]
  [ 7 64  2 86 90 55]
  [17 95  1 44 58 82]
  [68  3 87 53 62 60]]

 [[80 40 50  3 30 68]
  [65 18 29 63 65 37]
  [10 10 45 64 67 97]
  [24 66  9 95 83  6]
  [11  6 86 80 47 57]]]


In [ ]:
import time

In [ ]:
a=time.time()

In [ ]:
b=time.time()

In [ ]:
b-a

0.6314241886138916

In [ ]:
#Execution time [speed]
#LIST
a =[i for i in range(10000000)]
b= [i for i in range(10000000,20000000)]

c=[]
start= time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
end= time.time()

print(f"Total Duration {end-start}")

Total Duration 2.687835454940796


In [ ]:
# ARRAY
a= np.arange(10000000)
b= np.arange(10000000,20000000)

start= time.time()
c= a+b
end= time.time()

print(f"Total Duration {end-start}")

Total Duration 0.14126944541931152


In [ ]:
2.687835454940796/0.14126944541931152

19.026304286555717

In [ ]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])

In [ ]:
a+b

array([2, 4, 6, 8])

In [ ]:
# MEMORY
import sys

In [ ]:
#LIST
a =[i for i in range(10000000)]
sys.getsizeof(a)

89095160

In [ ]:
# ARRAY
a= np.arange(10000000)
sys.getsizeof(a)

40000112

In [ ]:
89095160/40000112

2.2273727633562626

In [ ]:
# ARRAY FUNCTIONS.

#ndim
#shape
#reshape


In [ ]:
a= np.random.randint(1,10, size=(3,3))

In [ ]:
a

array([[1, 9, 3],
       [6, 2, 5],
       [6, 7, 1]])

In [ ]:
a.size   # tells  total number of elements in an array/matrix

9

In [ ]:
a.itemsize  # tells how much space an single element is occupying  in memory

4

In [ ]:
a= np.random.randint(1,10, size=(3,3))

In [ ]:
a

array([[3, 4, 6],
       [7, 5, 3],
       [9, 8, 6]])

In [ ]:
b= a.astype("object")

In [ ]:
b

array([[3, 4, 6],
       [7, 5, 3],
       [9, 8, 6]], dtype=object)

In [ ]:
b.size

9

In [ ]:
b.itemsize

8

In [ ]:
c= np.array([[3,"2333"],["q","we"]])

In [ ]:
c

array([['3', '2333'],
       ['q', 'we']], dtype='<U11')

In [ ]:
c.itemsize

44